### ISSUE TITLE
A roadmap for the book?

### ISSUE THREAD

**Issue by alehander42** [intermezzOS/kernel#55] opened 2016-07-03 18:05 UTC
Hey, 

I am following this project with great interest. I wonder if there is any kind of schedule or a plan for the next chapters (because I want to start playing with osdev using this project when it gets to the printing to screen stuff and I want to schedule my other side projects now)

**Comment by steveklabnik** [comment] 2016-07-05 18:43
Hey @alehander42 ,

There's no schedule; this is 100% in my free time, and sometimes I have a lot of time for it, and sometimes I don't. There is a rough plan; you can see how `SUMMARY.md` in the book repo has some future chapters sketched out, and the code here is farther ahead. However, one reason I haven't written the VGA chapter yet is I'm not sure that the code here is the best I can do; I might try a more experimental design. We'll see!

(Closing as it's not a bug, but feel free to keep posting with more questions and we can talk about it if you have more thoughts.)

**Closed by steveklabnik** 2016-07-05 18:43 UTC
